# NOTE: Do not edit, file was generated by jhconvert

Name: python-xklavier
Version: 0.2
Release: %mkrel 1
Summary: Python binding for libxklavier
License: LGPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/external/python-xklavier/python-xklavier-0.2.tar.gz

Requires: gtk+2 >= 2.2.0
Requires: libxklavier15 >= 4.0
Requires: python-gobject >= 2.6.2
Requires: python  

BuildRequires: gtk+2-devel >= 2.2.0
BuildRequires: libxklavier-devel >= 4.0
BuildRequires: python-gobject-devel >= 2.6.2
BuildRequires: libpython-devel  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)


%description
Python binding for libxklavier.

%prep
%setup -q -n python-xklavier-0.2


%build
%define __libtoolize true
%configure --disable-static
make

%install
rm -rf %{buildroot}
make DESTDIR=%{buildroot} install


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%{python_sitelib}/*

